/** Permisos mínimos por ruta del panel admin (`route.data.permissions`). */
export const ADMIN_ROUTE_PERMISSIONS = {
  dashboard: ['nav.dashboard_admin'],
  usuarios: ['users.read', 'nav.usuarios'],
  establecimientos: ['nav.establecimientos'],
  clientes: ['customers.read', 'nav.clientes_list'],
  tipoClientes: ['customer-types.read', 'nav.tipo_clientes'],
  productos: ['products.read', 'nav.productos'],
  conjuntosPacks: ['nav.conjuntos_packs'],
  servicios: ['nav.servicios'],
  categorias: ['categories.read', 'nav.categorias'],
  marcas: ['brands.read', 'nav.marcas'],
  laboratorios: ['laboratories.read', 'nav.laboratorios'],
  unidades: ['units.read', 'nav.unidades'],
  formasFarmaceuticas: ['pharma-forms.read', 'nav.formas_farmaceuticas'],
  principiosActivos: ['active-principles.read', 'nav.principios_activos'],
  viasAdministracion: ['admin-routes.read', 'nav.vias_administracion'],
  proveedores: ['suppliers.read', 'nav.proveedores'],
  ordenesCompra: ['purchases.read', 'nav.ordenes_compra'],
  recepcionMercaderia: ['purchases.read', 'purchases.receive', 'nav.recepcion_mercaderia'],
  reporteComprasSugerido: ['purchases.read', 'nav.reporte_compras_sugerido'],
  comparativoPrecios: ['purchases.read', 'nav.comparativo_precios'],
  series: ['nav.series'],
  zonas: ['nav.zonas'],
  importarPrecios: ['nav.importar_precios'],
  puntoVenta: ['nav.punto_venta'],
  cajaChicaPos: ['nav.caja_chica_pos'],
  comprobanteElectronico: ['billing.read', 'billing.write', 'nav.comprobante_electronico'],
  notasVenta: ['nav.notas_venta'],
  resumenes: ['billing.read', 'billing.write', 'nav.resumenes'],
  anulaciones: ['nav.anulaciones'],
  cotizaciones: ['nav.cotizaciones'],
  inventarioMovimientos: ['inventory.read', 'nav.inventario_movimientos'],
  traslados: ['inventory.read', 'nav.traslados'],
  devolucionRetiro: ['nav.devolucion_retiro'],
  reporteKardex: ['inventory.read', 'nav.reporte_kardex'],
  reporteInventario: ['inventory.read', 'nav.reporte_inventario'],
  kardexValorizado: ['inventory.read', 'nav.kardex_valorizado'],
  lotes: ['inventory.read', 'nav.lotes'],
  salidaVentaLotes: ['inventory.read', 'inventory.write', 'nav.salida_venta_lotes'],
  cadenaFrio: ['inventory.read', 'inventory.write', 'nav.cadena_frio'],
  retenciones: ['nav.retenciones'],
  percepciones: ['nav.percepciones'],
  ordenesPedido: ['nav.ordenes_pedido'],
  grRemitente: ['nav.gr_remitente'],
  grTransportista: ['nav.gr_transportista'],
  transportistas: ['nav.transportistas'],
  conductores: ['nav.conductores'],
  vehiculos: ['nav.vehiculos'],
  direccionesPartida: ['nav.direcciones_partida'],
  reportes: ['nav.reportes_panel'],
  contabilidadExportarReporte: ['nav.contabilidad_exportar_reporte'],
  contabilidadResumenVenta: ['nav.contabilidad_resumen_venta'],
  contabilidadExportarFormatos: ['nav.contabilidad_exportar_formatos'],
  contabilidadReporteResumido: ['nav.contabilidad_reporte_resumido'],
  libroMayor: ['nav.libro_mayor'],
  sireVentas: ['nav.sire_ventas'],
  sireCompras: ['nav.sire_compras'],
  finanzasMovimientos: ['nav.finanzas_movimientos'],
  transacciones: ['nav.transacciones'],
  finanzasIngresos: ['nav.finanzas_ingresos'],
  cuentasCobrar: ['nav.cuentas_cobrar'],
  cuentasPagar: ['purchases.read', 'purchases.write', 'nav.cuentas_pagar'],
  pagos: ['nav.pagos'],
  balance: ['nav.balance'],
  ingresosEgresosMedioPago: ['nav.ingresos_egresos_medio_pago'],
  reporteDigemid: ['pharmaceutical.read', 'nav.reporte_digemid'],
  recetas: ['prescriptions.read', 'prescriptions.write', 'nav.recetas'],
  medicos: ['medicos.read', 'medicos.write', 'nav.medicos'],
  cie10: ['pharmaceutical.read', 'nav.cie_10'],
  reportePsicotropicos: ['pharmaceutical.read', 'nav.reporte_psicotropicos'],
  recepcionProductosFarmaceuticos: ['nav.recepcion_productos_farmaceuticos'],
} as const;
